### PR TITLE
Add asyncpg, uvloop and asyncio for framework Tornado

### PR DESCRIPTION
**Pull request by maximzah**

### CODE REVIEW

**Comment by maximzah** [comment]
@stalkerg We added asyncpg, async/await to the Tornado framework. Can you please see PR, do we understand you correctly?

**Comment by stalkerg** [comment]
Yes, looks good for me. Thank you. 

But it's a single process only, usually, if you need more raw performance you should run several processes. (it's true for your aiohttp tests too)
You can read about it here: https://www.tornadoweb.org/en/stable/httpserver.html
Something like this:
```python
server.bind(8080)
server.start(0)
``` 
instead just `server.listen(8080, '0.0.0.0')`

For example for my project I use one process for websocket communication only and extra 3 processes for rendring templates and nginx make load balance.

**Comment by maximzah** [comment]
@stalkerg thank you. We made new benchmarks for Tornado with all the changes.

**Tornado + momoko**
screenshot at feb 28 10-28-35

**Tornado + uvloop + asyncpg + start server with "listen" ([current PR](https://github.com/startmatter/python-frameworks-benchmark/pull/3))**
screenshot at feb 28 10-35-59

**Tornado + uvloop + asyncpg + start server with "bind" and "start"**
screenshot at feb 28 10-40-36

As you can see, the result has changed slightly. Are you sure that your options should give a big advantage to Tornado? 
In any case, 15% is better than nothing, so I think we'll merge it and update our tables in article

**Comment by stalkerg** [comment]
I will make my own tests at the weekend. It's strange because you will have much more latency and timeout with async. 
And yes, 800 req/sec it's too slow, for my tests I have > 8000 for Tornado and > 14000 for aiohttp. (two years ago)
Basically, I had similar results to https://www.techempower.com/benchmarks/

**Comment by stalkerg** [comment]
@maximzah 

I made my own tests on Ryzen 7 2700X, without gunicorn and docker (by default docker has significant network overhead). Also, I tested a new Tornado 6 (released yesterday).
Results very interesting:
### aiohttp
```
Running 30s test @ http://127.0.0.1:8080/db
  12 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   143.25ms  330.87ms   6.85s    89.43%
    Req/Sec   239.85     31.78   366.00     72.69%
  86400 requests in 30.00s, 18.87MB read
  Socket errors: connect 0, read 0, write 0, timeout 190
Requests/sec:   2880.29
Transfer/sec:    644.13KB
```

### aiohttp + uvloop
```
Running 30s test @ http://127.0.0.1:8080/db
  12 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   103.35ms   72.39ms   1.60s    77.26%
    Req/Sec   322.21     26.79   416.00     71.63%
  115743 requests in 29.99s, 25.28MB read
Requests/sec:   3859.07
Transfer/sec:    863.01KB
```

### tornado 5.1.1 + momoko
```
Running 30s test @ http://127.0.0.1:8080/db
  12 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   220.64ms   13.72ms 255.94ms   87.71%
    Req/Sec   148.05     31.56   202.00     64.15%
  53153 requests in 30.00s, 13.79MB read
Requests/sec:   1771.55
Transfer/sec:    470.57KB
```

### tornado 5.1.1 + uvloop + momoko
```
Running 30s test @ http://127.0.0.1:8080/db
  12 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   234.08ms   26.39ms 464.13ms   87.37%
    Req/Sec   139.77     28.91   320.00     86.10%
  50053 requests in 30.00s, 13.08MB read
  Socket errors: connect 0, read 0, write 0, timeout 4
Requests/sec:   1668.30
Transfer/sec:    446.40KB
```

### tornado 5.1.1 + asyncio + asyncpg
```
Running 30s test @ http://127.0.0.1:8080/db
  12 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   260.11ms   29.70ms 504.75ms   96.99%
    Req/Sec   125.78     22.59   346.00     85.79%
  45097 requests in 30.00s, 11.78MB read
Requests/sec:   1503.08
Transfer/sec:    402.19KB
```

### tornado 5.1.1 + uvloop + asyncio + asyncpg
```
Running 30s test @ http://127.0.0.1:8080/db
  12 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   225.86ms  473.34ms  11.33s    98.63%
    Req/Sec   149.68     35.53   402.00     82.10%
  53551 requests in 29.99s, 13.99MB read
  Socket errors: connect 0, read 0, write 0, timeout 521
Requests/sec:   1785.36
Transfer/sec:    477.72KB
```

### tornado 6.0.0 + asyncio + asyncpg
```
Running 30s test @ http://127.0.0.1:8080/db
  12 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     4.29s     4.88s   11.29s    59.23%
    Req/Sec   150.70    111.38   764.00     70.32%
  54253 requests in 30.00s, 14.07MB read
  Socket errors: connect 0, read 0, write 0, timeout 1048
Requests/sec:   1808.43
Transfer/sec:    480.37KB
```

### tornado 6.0.0 + uvloop + asyncio + asyncpg
```
Running 30s test @ http://127.0.0.1:8080/db
  12 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   178.21ms  251.40ms   5.21s    90.82%
    Req/Sec   185.63     25.63   284.00     72.82%
  66770 requests in 30.00s, 17.32MB read
  Socket errors: connect 0, read 0, write 0, timeout 60
Requests/sec:   2225.97
Transfer/sec:    591.27KB
```

### tornado 5.1.1 + asyncio + asyncpg + fork
```
Running 30s test @ http://127.0.0.1:8080/db
  12 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    41.70ms   11.92ms 475.76ms   81.90%
    Req/Sec   792.26     55.16     1.07k    70.93%
  283214 requests in 30.00s, 74.01MB read
  Socket errors: connect 0, read 0, write 0, timeout 10
Requests/sec:   9439.73
Transfer/sec:      2.47MB
```

### tornado 5.1.1 + uvloop + asyncio + asyncpg + fork
```
Running 30s test @ http://127.0.0.1:8080/db
  12 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    35.76ms    7.15ms 210.84ms   71.33%
    Req/Sec     0.93k    44.53     1.08k    70.25%
  331838 requests in 29.95s, 86.71MB read
Requests/sec:  11080.35
Transfer/sec:      2.90MB
```

### tornado 6.0.0 + asyncio + asyncpg + fork
```
Running 30s test @ http://127.0.0.1:8080/db
  12 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    34.90ms   71.52ms   7.70s    97.90%
    Req/Sec     0.94k   169.82     1.35k    75.87%
  322578 requests in 30.00s, 83.68MB read
  Socket errors: connect 0, read 0, write 0, timeout 243
Requests/sec:  10752.49
Transfer/sec:      2.79MB
```

### tornado 6.0.0 + uvloop + asyncio + asyncpg + fork
```
Running 30s test @ http://127.0.0.1:8080/db
  12 threads and 400 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    27.94ms  165.20ms  14.50s    99.51%
    Req/Sec     1.18k   210.07     1.65k    65.46%
  403742 requests in 30.00s, 104.73MB read
  Socket errors: connect 0, read 0, write 0, timeout 622
Requests/sec:  13458.78
Transfer/sec:      3.49MB
```

As you can see, in the real environment when you have multiple processes performance much better. 
And even for single process performance with Tornado 6 and uvloop not so bad if compare with aiohttp. 

For forking I used next code:
```python
    sockets = tornado.netutil.bind_sockets(8080)
    tornado.process.fork_processes(0)
    server = HTTPServer(application)
    server.add_sockets(sockets)
    ioloop = IOLoop.current()
    application.db = ioloop.run_sync(partial(init_db))
    ioloop.start()
```

**Comment by stalkerg** [comment]
Probably I should recheck my tests again:
https://github.com/tornadoweb/tornado/commit/64de184a785604a3aac2ed8020e246b701d81278

**Pull request closed without merging**
